name = "blur-flower"
main = "./src/main.js"
compatibility_date = "2023-01-01"

routes = [
	{ pattern = "flower.hman.io", custom_domain = true },
	{ pattern = "0x8.io", custom_domain = true }
]

workers_dev = false
preview_urls = false

[observability]
enabled = false

[observability.logs]
invocation_logs = false

[placement]
mode = "smart"

[assets]
directory = "./pub/"
not_found_handling = "single-page-application"